version: '3.5'

services:

    felicity_fe:
        container_name: felicity_fe
        restart: unless-stopped
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        depends_on:
            - felicity_be
        networks:
            - felicitynet
        command: bash -c "cd vite && yarn dev"

    felicity_be:
        container_name: felicity_be
        restart: unless-stopped
        build:
            context: ./backend/
        environment:
            - POSTGRES_SERVER=felicity_db
            - POSTGRES_DB=felicity_lims
            - POSTGRES_USER=felicity
            - POSTGRES_PASSWORD=felicity
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./backend/:/app
        expose:
            - "8000"
        ports:
            - 8000:8000
        depends_on:
            - felicity_db
        networks:
            - felicitynet
        command: bash -c "cd felicity_lims && ./felicity.sh"

    felicity_db:
        container_name: felicity_db
        image: postgres:12
        restart: unless-stopped
        environment:
            - POSTGRES_DB=felicity_lims
            - POSTGRES_USER=felicity
            - POSTGRES_PASSWORD=felicity
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres/init/:/docker-entrypoint-initdb.d/
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - felicitynet

    pgadmin:
        container_name: felicity.pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - felicitynet
        restart: unless-stopped
        depends_on:
            - felicity_db

    # nginx:
    #     container_name: felicity.nginx
    #     image: nginx:latest
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./services/nginx:/etc/nginx/conf.d
    #     depends_on:
    #         - backend
    #         - frontend

volumes:
    db-data:
    pgadmin:

networks:
    felicitynet:
        driver: bridge